FROM debian:trixie-slim

RUN apt-get update && apt-get install --no-install-recommends -y \
    osm2pgsql postgresql-client && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /cyclosm
WORKDIR /cyclosm

CMD sh scripts/docker-startup.sh import
